$(document).on("click",".diyi",function (e) { //.siblings().removeClass("left02_active")
    $(this).addClass("left02_active")
    $(".shahu").removeClass("left02_active")
    $(".tangkeng").removeClass("left02_active")
    $(".dier").removeClass("left02_active")
    $(".bilin").removeClass("left02_active")
    $(".eft02_right2").show()
    $(".eft02_right3").hide()
    $(".eft02_right_shahu").hide()
    $(".eft02_right_bilin").hide()
    $(".eft02_right_tangkeng").hide()
})
$(document).on("click",".shahu",function (e) {
    $(this).addClass("left02_active")
    $(".diyi").removeClass("left02_active")
    $(".tangkeng").removeClass("left02_active")
    $(".dier").removeClass("left02_active")
    $(".bilin").removeClass("left02_active")
    $(".eft02_right2").hide()
    $(".eft02_right3").hide()
    $(".eft02_right_shahu").show()
    $(".eft02_right_bilin").hide()
    $(".eft02_right_tangkeng").hide()
})
$(document).on("click",".tangkeng",function (e) {
    $(this).addClass("left02_active")
    $(".diyi").removeClass("left02_active")
    $(".shahu").removeClass("left02_active")
    $(".dier").removeClass("left02_active")
    $(".bilin").removeClass("left02_active")
    $(".eft02_right2").hide()
    $(".eft02_right3").hide()
    $(".eft02_right_shahu").hide()
    $(".eft02_right_bilin").hide()
    $(".eft02_right_tangkeng").show()
})
$(document).on("click",".dier",function (e) {
    $(this).addClass("left02_active")
    $(".diyi").removeClass("left02_active")
    $(".shahu").removeClass("left02_active")
    $(".tangkeng").removeClass("left02_active")
    $(".bilin").removeClass("left02_active")
    $(".eft02_right2").hide()
    $(".eft02_right3").show()
    $(".eft02_right_shahu").hide()
    $(".eft02_right_bilin").hide()
    $(".eft02_right_tangkeng").hide()
})
$(document).on("click",".bilin",function (e) {
    $(this).addClass("left02_active")
    $(".diyi").removeClass("left02_active")
    $(".shahu").removeClass("left02_active")
    $(".tangkeng").removeClass("left02_active")
    $(".dier").removeClass("left02_active")
    $(".eft02_right2").hide()
    $(".eft02_right3").hide()
    $(".eft02_right_shahu").hide()
    $(".eft02_right_bilin").show()
    $(".eft02_right_tangkeng").hide()
})


//
// $(document).on("click",".eft02_right1 #r1",function (e) {
//     $(".eft02_right2").show()
//     $(".eft02_right3").hide()
// })
// $(document).on("click",".eft02_right1 #r2",function (e) {
//     $(".eft02_right3").show()
//     $(".eft02_right2").hide()
// })
